<%-- 
    Document   : F1
    Created on : 3 Jan, 2023, 9:55:01 PM
    Author     : Grissna
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>

<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="style.css">
        <title>ELECTRO</title>
    </head>

    <body>

        <div class='banner'>
            <div>
                <h1 style='text-transform: uppercase; text-align: center; padding-top: 50px;'>
                    <Picture>FANTASY F1</Picture>
                </h1>
            </div>
        </div>


        <nav>
            <ul>
                <li><a href='about1.jsp'>About Us</a></li>
                <li><a href='game.jsp'>Games</a></li>
                <li><a href='video.jsp'>Gameplay</a></li>
                <li><a href='index.html'>Sign Up</a></li>

            </ul>
        </nav>


        <br><br>
        <br>
        <br>

    <p1><b><h2> <p style="color:red">WHAT IS FORMULA 1??</p></h2><b></p1><br>
                <b>Formula One</b><u>(also known as Formula 1 or F1)</u> is the highest class of international racing for open-wheel single-seater formula racing cars sanctioned by the <i>Fédération Internationale de l'Automobile (FIA).</i>The World Drivers' Championship, which became the FIA Formula One World Championship in 1981, has been one of the premier forms of racing around the world since its inaugural season in 1950.<br>
                <br>Formula One cars are the fastest regulated road-course racing cars in the world, owing to very high cornering speeds achieved through the generation of large amounts of aerodynamic downforce.<br>
                Much of this downforce is generated by front and rear wings, which have the side effect of causing severe turbulence behind each car. <br> 

                <br>Major changes to the cars for the 2022 season has seen greater use of ground effect aerodynamics, and modified wings to reduce the turbulence behind the cars, with the goal of making overtaking easier.The cars are dependent on electronics and aerodynamics,suspension and tyres.<br>
                <br>For more information <a href="https://www.formula1.com/" style="color:black"> Formula 1</a><br></p1>
                <br><br><br><br>

                <h2><p style="color:red">GAMING</p></h2>
                Ever since Pole Position in 1982, Formula One (F1) has always played a part of the racing genre in video games. Early Formula One games were typically arcade racing games, before Formula One Grand Prix (1991) popularized Formula One racing simulations on home computers.<br> 

                <br>As video games continued to advance and home consoles became more popular, F1 made the transition away from arcades. Super Monaco GP (1989) proved a hit on the Sega Megadrive, and enjoyed input from Ayrton Senna for its 1992 sequel, while games such as Grand Prix (1992) started to edge the genre toward more simulation-style features.<br> 
                <br>The F1 license was shared between Electronic Arts - who continued to produce a yearly edition as part of its successful roster of sports games - and Sony between 2000 and 2003, crossing the launch of the PlayStation 2.<br> The first game for the eighth-generation consoles (PlayStation 4 and Xbox One) was F1 2015, but with F1 2017 came an important landmark for the series: the establishment of an official Esports series.<br><br> 

                <h2><p style="color:red">OTHER UPDATES</p></h2>
                <li style='text-align: center'>The F1 Fantasy gaming section brings the latest video game news
                    reviews of the most exciting releases</li>
                <li style='text-align: center'>and interviews with the industry’s biggest names,
                    We cover everything from PlayStation and Xbox blockbusters</li> 
                <li style='text-align: center'>To quirky Nintendo games</li>
                <li style='text-align: center'> To the cool indie gems on PC and Android that you might otherwise miss.</li>
                <br><br><br><br><br>

                <img src="img\f1-mobile-racing-2.png" alt="Trulli" width="900" height="600" ><br><br><br>

                </body>
                </html>
