<%-- 
    Document   : game
    Created on : 5 Jan, 2023, 3:26:01 PM
    Author     : Grissna
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="game.css">
    <title>IMAGE</title>
</head>

<body>


<h1>F1 22 GAME</h1>
    
<p><b>F1 22 is a racing video game developed by Codemasters and published by EA Sports. It is the fifteenth entry in the F1 series by Codemasters. The game holds an official license of the 2022 Formula One and Formula 2 championships.The game was released for Microsoft Windows, PlayStation 4, PlayStation 5, Xbox One, and Xbox Series X/S on 1 July 2022.</p><br>

<img src="img\F122.1.png" alt="Trulli" width="900" height="500" ><br><br><br><br>

<h2>Gameplay</h2>
<h3>New cars and New Regulations</h3> 
<p>2022 has brought in sweeping changes to the Formula 1 regulations. These new rules are designed to promote overtaking and bring the cars closer together in terms of performance.
The new regs have certainly made a difference. For a start, Mercedes are no longer top dogs, with Ferrari taking their place and being challenged by Red Bull.<br> 
<br>This is in part thanks to the cars having less downforce generated by the wings and the addition of ground effect airfoils underneath the cars. This means the 2022 cars will be faster in quick corners and slower in slow corners.Let's not forget about the new tyres either, which are much larger at 18 inches in size. In F1 22, the 2022 cars will be vastly different to drive, but both more challenging and rewarding than previous years.<br>
<br>Codemasters has updated the physics to reflect the new aero rules and reworked the tyre model, making the handling more realistic.<br> 

<img src="img\F122.2.png" alt="Trulli" width="800" height="500" ><br><br><br><br>


<h3>Adaptive AI</h3>
<p>Adaptive AI will let players race against "AI racers tailored to match their skill level." There are also new customisation options, with new 'immersive' and 'broadcast' race day options.<br></p>


<h3>My Team & Career Mode</h3>
<p>While online multiplayer has become a more important aspect to the F1 games, it's single player where it really shines. In particular My Team, which is one of the most enjoyable and in-depth Career Modes you'll find in racing gaming.
Of course, the vehicle performance index and driver ratings will get an update. The same is true for the Formula 2 drivers, although we won't see the 2022 field until around November time like in 2021.<br>
<br>
It's the specifics of car and team development that we're really interested in though. Due to the cost cap measures which have been brought in this year, you may be limited in how much you can spend in a season.
It's not clear how Codemasters will implement these measures, but it'll be very interesting to see how they handle it. What we could see more effort towards though is the media outside of races, where it could be more like what we see from Formula 1's actual media outlets.<br>

<br>Codemasters has confirmed the fan-favourite My Team mode is returning in F1 22. This time, players will choose a starting budget and three entry scenarios: Newcomer, Challenger, and Front Runner.<br>

<img src="img\F122.3.jpg" alt="Trulli" width="800" height="500" ><br><br><br><br></p>

<h3>Online multiplayer</h3>
<p>As expected, two-player split-screen and online multiplayer will return in F1 22.
Codemasters and EA have confirmed F1 22 will feature cross-gen multiplayer, meaning PS4 and PS5 players can race together online. Xbox Series X|S and Xbox One players will also be able to compete against each other online.<br></p>

<h3>Other Features</h3>
<p>F1 22 also features immersive broadcast options, designed after televised Formula One broadcasts, as well as interactive pit stops.<br>

<br>Cross-play makes its debut with support on the Social Race and Two Player Career modes for Xbox Series X/S, PlayStation 5 and PC via Steam and Origin/EA Desktop/Epic Games Store.<br>
<br>The game also introduces a customisable hub mode called F1 Life to allow players to collect supercars, clothing and accessories.The game is also confirmed to support virtual reality for PC via Oculus Rift, or HTC Vive, virtual reality headsets.<br></p>

<img src="img\F122.4.jpg" alt="Trulli" width="900" height="500" ><br><br><br><br>

<h2>Development and Release</h2>
<p>F1 22 was revealed on 21 April 2022, with both Codemasters and EA Sports returning to work on the game.It is an official video game of the 2022 Formula One and Formula 2 championships,alongside F1 Manager 2022 of Frontier Developments.The game was launched on 1 July 2022, for Microsoft Windows, PlayStation 4, PlayStation 5, Xbox One, and Xbox Series X/S platforms via Steam, Epic Games Store and Origin, which is on the weekend of the 2022 British Grand Prix.The Champions Edition of the game was released three days earlier, on 28 June 2022.<br></p> 
<br></b><br><br><br><br>
</body>
</html>

